spring:
  datasource:
    name: mydb
    url: jdbc:mysql://generaltestdb.c6fbft1y5usq.ap-southeast-2.rds.amazonaws.com/schooldb?allowMultiQueries=true&useUnicode=true&charaterEncoding=utf-8
    username: admin
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver